### ISSUE TITLE
Fix unit test on build farm for new service functions

### ISSUE THREAD

**Issue by JanStaschulat** [ros2/rclc#49] opened 2021-02-16 14:26 UTC
@norro 
Hi Arne, could you have a look, why these unit tests with services fail?
https://build.ros2.org/job/Rpr__rclc__ubuntu_focal_amd64/71/#showFailuresLink

Option A)
- you could use this PR for the fix: https://github.com/ros2/rclc/pull/46
- that means to create a branch based on micro-ros/rclc:master and then 
-  create a PR to micro-ros/rclc:master.
- then these changes will be considered in the PR.

Option B)
- I merge this PR https://github.com/ros2/rclc/pull/46 now
- You start fresh from ros2/rclc:master

**Comment by JanStaschulat** [comment] 2021-02-16 18:49
@norro: The expected sequence id is 1, however for Rolling release in the docker container the returned sequence id is different in each unit test. As this is not  part of the executor functionality, but rather a RCL/RMW issue, I would propose to omit this ASSERT in all relevant unit_tests with services/clients:

https://github.com/ros2/rclc/blob/c5b0d3d08a6f4fa70d3e056a4f3ff70158c808c3/rclc/test/rclc/test_executor.cpp#L2081

**Comment by norro** [comment] 2021-02-17 07:07
Agreed, I wouldn't have a clue how to resolve this.
Should we / can we report an issue upstream (in rcl/rmw) to have this fixed upstream?

**Comment by JanStaschulat** [comment] 2021-02-17 09:51
Yes, that is a good idea. you could also point out, that it is only an issue on the build farm and not in a normal `colcon test` with Github Action.

**Comment by norro** [comment] 2021-02-19 13:21
@JanStaschulat Could you please write the upstream issue in rcl/rmw? I don't have enough knowledge of rcl/rmw to be able to phrase the issue, I'm afraid.
After the issue is created, I suggest to close this issue.

**Comment by JanStaschulat** [comment] 2021-02-22 08:07
@norro created an issue for ros2/rclc https://github.com/ros2/rcl/issues/892. I would keep the issue open - because I referenced it in the ros2/rcl issue.

**Comment by JanStaschulat** [comment] 2021-02-22 17:27
@norro. As explained in the issue https://github.com/ros2/rcl/issues/892, the specification of `rcl_send_request` does not say to which value `seq_id` is initialized to. It is only guaranteed to be unique. 

Therefore we can not check this value (even though it is always "1" for Dashing and Foxy. So we can keep the unit test the way the are. I will remove these commented out lines. Then we can close this issue.

**Closed** 2021-02-23 08:10 UTC
